# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '画虚线' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MJExtension'
  # Pods for 画虚线

end
